# Generated by Django 4.1.4 on 2022-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_comments_id_alter_follows_id_alter_likes_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='following',
            new_name='followee',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='like_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_id',
        ),
    ]
