# Generated by Django 4.1.4 on 2022-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_rename_following_follows_followee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
