# Generated by Django 4.1.4 on 2022-12-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_posts_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
